
#!/bin/bash

#PBS -N ldm_ch22
#PBS -A UQ-IMB-CNSG
#PBS -o stdout
#PBS -e stderr
#PBS -l select=1:ncpus=1,pmem=10GB,walltime=00:30:00
#PBS -S /bin/bash

chr=22

bfile=../../../data/1000G_eur_chr22
out=1000G_eur_chr22


cd $PBS_O_WORKDIR

module load intel/2018.3.051  
gctb --bfile $bfile \
     --make-shrunk-ldm \
     --genmap ../../genetic_map/chr22.OMNI.interpolated_genetic_map \
     --write-ldm-txt \
     --out $out > $out.ldm.shrunk.log 2>&1   

